# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3628ca269878e8094c211050ab15cf0912bcd4fb64e2a69e71a8986ce17db228780f05210ecd64beb4150f79deb5e90f3b5909aedda8c59beea0a2a3da7b4c15

test:
  secret_key_base: 3a9e34aad4b49aeff57c1a27881e65380d84948be27b40ece4e70933c7d129fafa2eb5f24efee60eb17b12c20f08095a0d204affaefd9d10fac88cb8c4779851

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
